#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.SuperListView.Resource", IsApplication=false)]

namespace Xamarin.SuperListView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int supergv__columns = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int supergv__horizontalSpacing = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int supergv__verticalSpacing = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int superlv__empty = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int superlv__listSelector = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int superlv__moreProgress = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int superlv__progress = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int superlv__scrollbarStyle = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int superlv_mainLayoutID = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int swipe_progress_bar_height = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public static int empty = 2131034118;
			
			// aapt resource value: 0x7f050000
			public static int insideInset = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int insideOverlay = 2131034113;
			
			// aapt resource value: 0x7f050004
			public static int more_progress = 2131034116;
			
			// aapt resource value: 0x7f050002
			public static int outsideInset = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int outsideOverlay = 2131034115;
			
			// aapt resource value: 0x7f050005
			public static int ptr_layout = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int view_more_progress = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int view_progress = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int view_progress_gridview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int view_progress_listview = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] supergridview = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public static int supergridview_supergv__columns = 0;
			
			// aapt resource value: 2
			public static int supergridview_supergv__horizontalSpacing = 2;
			
			// aapt resource value: 1
			public static int supergridview_supergv__verticalSpacing = 1;
			
			public static int[] superlistview = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int superlistview_superlv__empty = 1;
			
			// aapt resource value: 0
			public static int superlistview_superlv__listSelector = 0;
			
			// aapt resource value: 2
			public static int superlistview_superlv__moreProgress = 2;
			
			// aapt resource value: 3
			public static int superlistview_superlv__progress = 3;
			
			// aapt resource value: 4
			public static int superlistview_superlv__scrollbarStyle = 4;
			
			// aapt resource value: 5
			public static int superlistview_superlv_mainLayoutID = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
