#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Resource", IsApplication=false)]

namespace Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f020000
			public static int colors = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int gplus_colors = 2130837505;
			
			// aapt resource value: 0x7f020003
			public static int pocket_background_colors = 2130837507;
			
			// aapt resource value: 0x7f020002
			public static int pocket_bar_colors = 2130837506;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int spbStyle = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public static int spb_background = 2130771981;
			
			// aapt resource value: 0x7f010001
			public static int spb_color = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public static int spb_colors = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public static int spb_generate_background_with_colors = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public static int spb_gradients = 2130771983;
			
			// aapt resource value: 0x7f010008
			public static int spb_interpolator = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int spb_mirror_mode = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public static int spb_progressiveStart_activated = 2130771980;
			
			// aapt resource value: 0x7f010006
			public static int spb_progressiveStart_speed = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int spb_progressiveStop_speed = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int spb_reversed = 2130771977;
			
			// aapt resource value: 0x7f010004
			public static int spb_sections_count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int spb_speed = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int spb_stroke_separator_length = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int spb_stroke_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070001
			public static int spb_default_mirror_mode = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int spb_default_progressiveStart_activated = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int spb_default_reversed = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030004
			public static int gplus_color_1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int gplus_color_2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int gplus_color_3 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int gplus_color_4 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int holo_blue_dark = 2130903048;
			
			// aapt resource value: 0x7f03000a
			public static int holo_green_dark = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int holo_purple_dark = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int holo_red_dark = 2130903052;
			
			// aapt resource value: 0x7f030009
			public static int holo_yellow_dark = 2130903049;
			
			// aapt resource value: 0x7f030000
			public static int pocket_color_1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int pocket_color_2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int pocket_color_3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int pocket_color_4 = 2130903043;
			
			// aapt resource value: 0x7f03000d
			public static int spb_default_color = 2130903053;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int spb_default_stroke_separator_length = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int spb_default_stroke_width = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public static int spb_interpolator_accelerate = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int spb_interpolator_acceleratedecelerate = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int spb_interpolator_decelerate = 2131296258;
			
			// aapt resource value: 0x7f090003
			public static int spb_interpolator_linear = 2131296259;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public static int spb_default_interpolator = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int spb_default_sections_count = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int spb_default_speed = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080003
			public static int GoogleNowProgressBar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public static int GooglePlusProgressBar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public static int SmoothProgressBar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int Theme_SmoothProgressBarDefaults = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SmoothProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public static int SmoothProgressBar_spbStyle = 0;
			
			// aapt resource value: 13
			public static int SmoothProgressBar_spb_background = 13;
			
			// aapt resource value: 1
			public static int SmoothProgressBar_spb_color = 1;
			
			// aapt resource value: 11
			public static int SmoothProgressBar_spb_colors = 11;
			
			// aapt resource value: 14
			public static int SmoothProgressBar_spb_generate_background_with_colors = 14;
			
			// aapt resource value: 15
			public static int SmoothProgressBar_spb_gradients = 15;
			
			// aapt resource value: 8
			public static int SmoothProgressBar_spb_interpolator = 8;
			
			// aapt resource value: 10
			public static int SmoothProgressBar_spb_mirror_mode = 10;
			
			// aapt resource value: 12
			public static int SmoothProgressBar_spb_progressiveStart_activated = 12;
			
			// aapt resource value: 6
			public static int SmoothProgressBar_spb_progressiveStart_speed = 6;
			
			// aapt resource value: 7
			public static int SmoothProgressBar_spb_progressiveStop_speed = 7;
			
			// aapt resource value: 9
			public static int SmoothProgressBar_spb_reversed = 9;
			
			// aapt resource value: 4
			public static int SmoothProgressBar_spb_sections_count = 4;
			
			// aapt resource value: 5
			public static int SmoothProgressBar_spb_speed = 5;
			
			// aapt resource value: 3
			public static int SmoothProgressBar_spb_stroke_separator_length = 3;
			
			// aapt resource value: 2
			public static int SmoothProgressBar_spb_stroke_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
